In [74]:
import numpy as np 

In [75]:
array = np.array([1,2,3,4,5])
print(array[0])
print(array[1] + array[2])

1
5


In [76]:
array = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', array[0, 1])

2nd element on 1st row:  2


In [77]:
array = np.array([1, 2, 3, 4, 5])
x = array.copy()
array[0] = 42

print(array)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


Create View

In [78]:
array = np.array([1, 2, 3, 4, 5])
x = array.view()
x[0] = 43

print(array)
print(x)

[43  2  3  4  5]
[43  2  3  4  5]


Join Two Arrays 

In [79]:
array1 = np.array([1, 2, 3])

array2 = np.array([4, 5, 6])

array = np.concatenate((array1, array2))

print(array)

[1 2 3 4 5 6]


Join as two D arrays

In [80]:
array1 = np.array([1, 2, 3])

array2 = np.array([4, 5, 6])

array = np.stack((array1, array2), axis=1)

print(array)

[[1 4]
 [2 5]
 [3 6]]


In [81]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(array.shape)

(2, 4)


In [82]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(6, 2)

print(newarr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [83]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [84]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [85]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [86]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [87]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)
